### ISSUE TITLE
Selecting image layer makes plot go away

### ISSUE THREAD

**Issue by haesleinhuepf** [haesleinhuepf/napari-plot-profile#5]
Reported by @psobolewskiPhD in #3:

> 2) On a related note, switching to the image layer makes the graph disappear. This is somewhat odd, because I need to be on the image layer to so the cursor returns values in the status bar.

**Comment by haesleinhuepf** [comment]
Hi @psobolewskiPhD, 

this is intentional because the user interface of the plot doesn't show (yet) which shape layer is drawn. Thus, it only draws a shape layer if one is selected. It furthermore only draws the last drawn object in this layer.

How would you like to see this implemented? Should the plotting happen for all shape layers? Also, how about multiple lines in one shape layer? Would love to hear how you would shape the user interface...

Thanks!

**Comment by psobolewskiPhD** [comment]
It's hard to say, but at the least I would prefer if the previous graph persisted until a new shape layer was selected. If the user wants to clear it, maybe add a clear? The current behavior is just a bit disconcerting.
In my case, I was drawing a line, seeing the profile not resemble what I expected, so I want to the image layer to look at the values and the graph went *poof*. Having it persist here would be nice.

I'm not sure multiple different lines (by line i mean shape layer objects) is at all needed or intuitive. It's a line profile plot, so how would two different *lines* even be represented? Your multi-color example on the plugin homepage makes sense because it's the same *line* but on two images. 

This is how the basic function of the tool would work in my mind (with possible more advanced stuff available):
Draw line on a shape layer and get profile from last interacted image layer. 
Have option—a tab or something—where I could mark visibility of other image layers. 
So in your example gif, I would get purple by default and option to add green. This way there isn't an accidental 234 lines on top of each other—this happened to me with my widget when I got profiles for all slices of a z-stack!

**Comment by haesleinhuepf** [comment]
> It's hard to say, but at the least I would prefer if the previous graph persisted until a new shape layer was selected.

I agree and I can actually do this. It will be in the next release
https://github.com/haesleinhuepf/napari-plot-profile/commit/d37e3e6e80124bda14c46155a671037a6baac0ad

If you have an idea of how to deal with multiple lines, let me know!

**Comment by haesleinhuepf** [comment]
Ok, I added some functionality, that takes the currently selected line into account. Thus, if select a line, its profile will be plotted. If no line is selected, the last drawn line will be plotted. The new functionality is available in the [0.1.3 release](https://github.com/haesleinhuepf/napari-plot-profile/releases/tag/0.1.3). Would you mind testing it @psobolewskiPhD ?

**Comment by psobolewskiPhD** [comment]
Do you mean multiple lines on the plot or multiple lines drawn on the image?
To me the plot should only show values vs. a single drawn line, because combining different physical lines on a single plot doesn't make sense to me, as x represents distance along the line, but with 2+, which one?
What could be useful though is if the y-values could be from different channels, or in principle z or t slices. So x-stays the same–it's the physical line, but the dependent variable can change and be represented by color. This is your 2 image example on the homepage. 
Extending to stacks and t-slices in particular would be very useful, since the plot would then show kinetics of the value on the line plot. I would have loved such an option when doing calcium imaging during my post doc! (A stride option would be useful to reduce the number of plots. So if you have 200 t slices be able to make the lines show every 20th.)
For z-stacks, I could see profiles over a depth can also being useful—maybe for some colocalization analysis? 
Either way, this requires the one drawn line to persist across slices and this is sort of where I'm (very slowly) going with my widget. Personally, I think it may be clearer to the user if the plugin spawns it's own shapes layer. Launch plugin, get a layer and a line, adjust the line or draw a new one and get your data—with options (check boxes?) for behavior.

**Comment by psobolewskiPhD** [comment]
> Ok, I added some functionality, that takes the currently selected line into account. Thus, if select a line, its profile will be plotted. If no line is selected, the last drawn line will be plotted. The new functionality is available in the [0.1.3 release](https://github.com/haesleinhuepf/napari-plot-profile/releases/tag/0.1.3). Would you mind testing it @psobolewskiPhD ?

Update went fine, restarted napari, it shows 0.1.3, but I'm not seeing a change in behavior, either with 2 lines on one slice or going between two slices.

**Comment by haesleinhuepf** [comment]
> I'm not seeing a change in behavior

* If you select an image layer, the plot should stay (this is this issue, #5)
* If you go back and forth between slices and select lines, the plot should be done for the selected line (#7)

Both is shown in this video:
https://user-images.githubusercontent.com/12660498/130469091-510a6399-0aa3-4b25-9aa0-41649bee37c5.mp4

Can you check if this works for you?

**Comment by psobolewskiPhD** [comment]
Ok, it works. I have no idea why it wasn't before. God I'm useless!

BTW, if I close the plugin and open it then I have to click refresh to get the line profile and the live refresh doesn't work. I guess closing it just closes the widget and doesn't reinitialize the plugin?

**Comment by haesleinhuepf** [comment]
Thanks for testing!

> I guess closing it just closes the widget and doesn't reinitialize the plugin?

Good question! I hope in the future, we plugin developers can decide about that. At the moment, this is handled by napari.
